name: Deploy React + Vite to Github Pages

on:
  workflow_dispatch: 
  push:
    branches:
      - master
    
jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/code-eval

      # Build the project
      - name: Build project
        run: npm run build
        working-directory: ./frontend/code-eval
      
      # Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/code-eval/dist
